### ISSUE TITLE
Consider embedding an ed implementation

### ISSUE THREAD

**Issue by sidju** [casey/edmunge#1]
Currently this utility depends on `ed` being installed on the system, while not being packaged in a way that can declare and auto-resolve that dependency. One possible solution to this would be to use [add-ed](https://github.com/sidju/add-ed), an embeddable ed implementation in pure rust.

It would also give access to some additional small commands I've added, which could be quite helpful to users.

(I'm of course biased, as I would also appreciate the user feedback.)

**Comment by casey** [comment]
This is kind of a comedy program, until I got this notification I had totally forgotten that I had written it 😅 I don't think anyone uses it, but I think it would be unexpected if it didn't use the system installed `ed`. I think `ed` is actually required to be installed according to the POSIX spec. `add-ed` looks really cool though!
